server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bananavote?serverTimezone=UTC&characterEncoding=UTF-8
    username:
    password:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  profiles:
    include: jwt, oauth

logging:
    level:
      root: info
