server:
  servlet:
    context-path: /api/v1

spring:
  profiles:
    include: dev, jwt, oauth

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    open-in-view: false

logging:
  level:
    root: info

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  api-docs:
    groups:
      enabled: true

  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true

  paths-to-match:
    - /**
